version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"   # Map port 80 in the container to port 8081 on your localhost
    volumes:
      - .:/var/www/html  # Mount the current directory into the container
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
